### ISSUE TITLE
Overrides not respected

### ISSUE THREAD

**Issue by unhuman** [urbandecoder/couchbase#39]
When I use a wrapper cookbook to override the ['couchbase']['server']['version'] of Couchbase (and other attributes), it is not respected.

This is because the server.rb calculates an URL to get the resource.  But, that happens before the wrapper cookbook runs its attributes, so the URL is calculated on version 3.0.0, yet I'm trying to override to install Couchbase 3.0.2.

The workaround for this is to include all the calculation logic from attributes/server.rb in the wrapper cookbook attributes.

**Comment by citruspi** [comment]
You could also use `force_override`.

**Comment by juliandunn** [comment]
Don't use `force_override`. Just recompute the attributes yourself. I wrote a [blog post](https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/) way back when about this topic. It's by design.
