### ISSUE TITLE
Couchbase processes get restarted every chef run

### ISSUE THREAD

**Issue by unhuman** [urbandecoder/couchbase#44]
https://github.com/urbandecoder/couchbase/commit/d2da821bbdc9578442aa03323080ed6ea95d4643#diff-3e8bbb9796e1fb74295ceac72868245b

Did not make it into the 1.3.0 version on the Supermarket.  The modification of the node twice with these different attributes is not idempotent and I see the following in the Couchbase runs:
  * couchbase_node[self] action modify
  * couchbase_node[self] action modify

Since these modifications override eachother, they actually cause some of the processes to fail / be restarted.
Could we get a newer version of the cookbook published to the Supermarket?

**Comment by juliandunn** [comment]
Yep, I just tagged and released v1.3.1.

Note: I'm adding a note to the README.md that this cookbook is up for adoption. I find it hard to maintain because I don't use Couchbase anymore (haven't for >2 years ever since I joined Opscode^WChef).

**Comment by unhuman** [comment]
Hey - thanks for the quick response.  This was quite the doozie to find.  But now it's found.  Really appreciate it.  Otherwise we'd be maintaining a goofy branch.
